#include <cstdio>
#include "Independency/independency.hpp"
#include "parser.hpp"
#include "configurator.hpp"
#include "req_checker.hpp"
#include "builder.hpp"
#include <string>
#include <sstream>

const char* help =
"\nMake++, all-in-one project management system\n\n"
"Usage: mpp --in <config>\n"
"Flags: --help      : this help\n"
"       --in <file> : use file as project configuration\n"
"       --configure : compulsory configure the project and exit\n"
"       --clean     : delete all files generated by build process\n"
;

int main(int argc, char** argv)
{ independency::cli_parser cli(argc, argv);

  if (cli.count("--help")) { std::printf("%s\n", help); return 0; }

  if (!cli.count("--in")) { std::printf("Nothing to process\n"); return 0; }
  if (cli.count("--verbose")) { std::printf("Verbose mode\n"); }

  std::string filename = cli["--in"];
  independency::file file(filename);
  if (!file) { std::printf("Can't open %s\n", filename.c_str()); }

  independency::storage temp, stor;

  mpp_parser mp(stor);
  std::string mpp_file = file.read();
  std::stringstream mpp_stream(mpp_file);
  std::string line;
  while (std::getline(mpp_stream, line))
  { if (cli.count("--verbose")) { std::printf("%s\n", line.c_str()); }
    if (!mp.input(line)) { break; } }

  temp.parse(independency::file(std::string(".").append(filename)).read());

  if (cli.count("--configure"))
  { configurator(stor, temp).force().run();
    independency::file(std::string(".").append(filename))
      .write(temp.serialize());
    return 0; }

  if (cli.count("--clean")) { builder(stor, temp).clean(); return 0; }

  configurator(stor, temp).run();
  req_checker(stor).check();
  builder(stor, temp).build();

  independency::file(std::string(".").append(filename)).write(temp.serialize());

  return 0; }
